### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by madhushreeray30** [akeyless-community/steampipe-plugin-akeyless#1]
Thanks @devorbitus for this new plugin. Great work 🎉 !!
I think this plugin is a WIP hence I would like to give some recommendations on the structure built so far. This would help in faster development and ensure we follow our best practices:
The following suggestions are to make the plugin build process easier and faster.
Some of the suggestions may not be directly from your code but related to general norms practiced across Steampipe.

`config/akeyless.spc`
  - Are there so many config parameters required for authentication? If there are separate modes of authentication we should mention them separately in the same config.spc file.
  - Could you please update the `akeyless.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - Can you mention which of the parameters are required and which are optional as done in the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - We should mention values for all the parameters however commented out and the values should be in the format of the actual values (however incorrect)
  - We should also add details to set these parameters via the environment variable (if there are any)

`docs/tables/table_auth_method.md`
  - The name of the table should include the plugin name i.e `akeyless_auth_method`
  - The example queries should end with a `;`
  - The query format for the queries is out of sync can you please format it with [free formatter](https://www.freeformatter.com/sql-formatter.html#before-output) (2 indent spaces)
  - The example queries in the doc look a bit light. Could you please add 2 to 3 more example queries wherever possible?

`docs/index.md`
  - We have missed out on adding the `index.md` for this plugin. For reference, we can follow the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md)

`akeyless/auth_method.go`
- The column `auth_method_name` has incorrect description and transform function.

`akeyless/connection_config.go`
  - What are the required config parameters for this plugin? I see we have mentioned quite a lot in the `config.spc` file however we are addressing only a few here. If there are multiple combinations for authentication we should address all of them separately in the file and make sure all the required arguments are defined.
 
`akeyless/plugin.go`

  - Looks good 👍 
  - **Quick note** if we are planning to add more tables we should keep in mind that the table names should be in ascending order
 
`akeyless/utils.go`
  - We should add the configuration for loading the connection from the cache, which ensures throttling protection, etc. Therefore we should also add the configuration to set it back to the cache once the connection is successfully created. 
  - If we have environment variables for the plugin we should add the configuration to fetch the config arguments from the environment variables
  Reference > [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/namecheap/utils.go)

`README.md`
  - Best reference to start this doc will be the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md)
  
`CHANGELOG.md`
  - We need to create this file and draft an initial changelog release note, an example would be as follows:
```
## v0.0.1 [TBD]

_What's new?_

- New tables added
  - [akeyless_auth_method](https://hub.steampipe.io/plugins/akeyless-community/akeyless/tables/akeyless_auth_method)
```

`Makefile`

  - The file need not give commands based on the paths a simple command is good enough 
```
install:
	go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/akeyless-community/akeyless@latest/teampipe-plugin-akeyless.plugin *.go
```

`.vscode`
 - Please remove the `.vscode` folder
`Follow-up questions`

- A couple of follow-up questions:
    - How are we handling the resource not found errors?
    - Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
    - While working with the APIs did you encounter rate limit errors?
    - Please refer to https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information

Please let us know if you have questions, happy to help 👍

**Comment by devorbitus** [comment]
Hey @madhushreeray30 , thanks for the suggestions!

Here is a status update on the implemtation:

`config/akeyless.spc`
  - [x] Are there so many config parameters required for authentication? If there are separate modes of authentication we should mention them separately in the same config.spc file.
    - `I have since simplified the configuration by delegating the authentication to our CLI so that as we add new authentication methods they can be supported centrally instead of within each tool.`
  - [x] Could you please update the `akeyless.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - [x] Can you mention which of the parameters are required and which are optional as done in the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc)
  - [x] We should mention values for all the parameters however commented out and the values should be in the format of the actual values (however incorrect)
  - [x] We should also add details to set these parameters via the environment variable (if there are any)

`docs/tables/table_auth_method.md`
  - [x] The name of the table should include the plugin name i.e `akeyless_auth_method`
  - [x] The example queries should end with a `;`
  - [x] The query format for the queries is out of sync can you please format it with [free formatter](https://www.freeformatter.com/sql-formatter.html#before-output) (2 indent spaces)
  - [x] The example queries in the doc look a bit light. Could you please add 2 to 3 more example queries wherever possible?

`docs/index.md`
  - [ ] We have missed out on adding the `index.md` for this plugin. For reference, we can follow the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md)

`akeyless/auth_method.go`
  - [x] The column `auth_method_name` has incorrect description and transform function.
    - `This one was interesting as the "key" for that API call is actually the "name" of the auth method but the Terraform repository uses the term "path" so I am mirroring that here. I've updated the description and transform function to reflect that.`

`akeyless/connection_config.go`
  - [x] What are the required config parameters for this plugin? I see we have mentioned quite a lot in the `config.spc` file however we are addressing only a few here. If there are multiple combinations for authentication we should address all of them separately in the file and make sure all the required arguments are defined.
    - `I have since simplified the configuration by delegating the authentication to our CLI so that as we add new authentication methods they can be supported centrally instead of within each tool.`

`akeyless/plugin.go`

  - [x] Looks good 👍 
  - [x] **Quick note** if we are planning to add more tables we should keep in mind that the table names should be in ascending order

`akeyless/utils.go`
  - [ ] We should add the configuration for loading the connection from the cache, which ensures throttling protection, etc. Therefore we should also add the configuration to set it back to the cache once the connection is successfully created. 
  - [ ] If we have environment variables for the plugin we should add the configuration to fetch the config arguments from the environment variables
  Reference > [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/namecheap/utils.go)

`README.md`
  - [ ] Best reference to start this doc will be the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/README.md)
  
`CHANGELOG.md`
  - [x] We need to create this file and draft an initial changelog release note, an example would be as follows:
```
## v0.0.1 [TBD]

_What's new?_

- New tables added
  - [ ] [akeyless_auth_method](https://hub.steampipe.io/plugins/akeyless-community/akeyless/tables/akeyless_auth_method)
```

`Makefile`

  - [x] The file need not give commands based on the paths a simple command is good enough 
```
install:
	go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/akeyless-community/akeyless@latest/teampipe-plugin-akeyless.plugin *.go
```

`.vscode`
 - [x] Please remove the `.vscode` folder
`Follow-up questions`

**Comment by devorbitus** [comment]
Hey @madhushreeray30 ,

How do I get the stuff that goes at the top of the `docs/index.md` file like the images and their paths?

**Comment by madhushreeray30** [comment]
@devorbitus The image path for this plugin in README.md would be
`![image](https://hub.steampipe.io/images/plugins/akeyless-community/akeyless-social-graphic.png)`
For the index.md file it should be as follows
```
---
organization: akeyless-commuity
category: 
icon_url: "/images/plugins/akeyless-commuity/akeyless.svg"
brand_color: 
display_name: "Akeyless"
short_name: "akeyless"
description: 
og_description: 
og_image: "/images/plugins/akeyless-community/akeyess-social-graphic.png"
---
```
Please add the other details as per the plugin. I have just added the paths.
The graphics will be available once they are ready for this plugin from our end.

**Comment by devorbitus** [comment]
@madhushreeray30 sorry to do this but we had a rebranding and was hoping you could generate an updated picture like from https://akeyless.io

**Comment by akljph** [comment]
Here is the logo:

![Akeyless_Logo_RGB_Main Logo](https://github.com/akeyless-community/steampipe-plugin-akeyless/assets/126785627/04c4cbdf-afea-4a96-b9eb-9563d0c4602a)

**Comment by akljph** [comment]
@madhushreeray30 Can we also make sure that the path to the plugin is `https://hub.steampipe.io/plugins/akeyless/akeyless` ? And anything else it should just be `akeyless/akeyless`. Thanks!

Meaning as follows:

```
---
organization: Akeyless Security
category: 
icon_url: "/images/plugins/akeyless/akeyless.svg"
brand_color: 
display_name: "Akeyless"
short_name: "akeyless"
description: 
og_description: 
og_image: "/images/plugins/akeyless/akeyess-social-graphic.png"
---
```

**Comment by akljph** [comment]
@madhushreeray30  I also updated the README.md file and added an index.md file currently waiting to be merged. Just let me know if you have any objections to me merging please :)

**Comment by misraved** [comment]
Thanks @akljph and @devorbitus for this new plugin 👍 !!

Few points that remain unaddressed:
- We need to add the github org name to the plugin configuration in the `config/akeyless.spc` file:
```
connection "akeyless" {
  plugin = "akeyless-community/akeyless"  

  # Defines the type of access. Supported types: "api_key", "aws_iam", "azure_ad", "gcp", "universal_identity", "k8s", "jwt".
  #access_type = ""  

  # The access ID for authentication, required for all access types.
  #access_id = ""  

  # The access key or secret, paired with access_id.
  #access_key = ""  

  # API URL for the Akeyless Gateway, the default URL is https://api.akeyless.io.
  #api_url = ""  

  # JSON Web Token for JWT-based authentication.
  #jwt = ""  

  # User identity token for Universal Identity™ authentication.
  #uid_token = ""  

  # Audience for GCP authentication.
  #gcp_audience = ""  

  # Object ID for Azure AD authentication.
  #azure_object_id = ""  

  # Kubernetes service account token for Kubernetes-based authentication.
  #k8s_service_account_token = ""  

  # Name of the Kubernetes auth config.
  #k8s_auth_config_name = ""  

  # CA certificate for TLS verification of the Akeyless Gateway.
  #gateway_ca_cert = ""  
}
```

- In the plugin code, I see references to `akeylesslabs` org name, however the org name seems to be `akeyless-community`, could you please confirm which org is being used? On those lines, the `Makefile` should use `install:
	go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/akeyless-community/akeyless@latest/steampipe-plugin-akeyless.plugin *.go` instead of `install:
	go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/akeyless-community/akeyless@latest/steampipe-plugin-akeyless.plugin *.go`
	
- The table file names must include `akeyless`, for instance:
  - `table_item.go` -> `table_akeyless_item.go`
  - `table_role.go` -> `table_akeyless_role.go`
  
- `table docs`:
  - The example queries look a bit light and lack formatting. Could you please format the queries using https://www.freeformatter.com/sql-formatter.html setting it to `2 spaces per indent level`? 
  - Additionally, could you please add 2-3 example queries per table? Some ideas to design your query examples:
    - `akeyless_role` table could have example queries on `Roles created in the last 30 days`, and `Roles not modified in the last 90 days`. You could have a query expanding the JSON fields as well.

**Comment by akljph** [comment]
Thanks, @misraved. Answers below:

1) `akeyless-community` is the correct org name. We only import certain libraries from our `akeylesslabs` org for this to work.
2) I updated the makefile command
3) I updated the file names to `table_akeyless.go`
4) I updated the indentation and added more examples to the `table_docs`

Please let me know if this is good to go :)

Lastly, please update the header image for our integration with our new logo above and send us a link to use: https://github.com/akeyless-community/steampipe-plugin-akeyless/issues/1#issuecomment-2189031219

**Comment by misraved** [comment]
@akljph I think a few comments haven't been addressed as of now:
- https://github.com/akeyless-community/steampipe-plugin-akeyless/blob/main/config/akeyless.spc#L2 should include the org name in the plugin field. for instance, it should be `akeyless-community/akeyless`
- https://github.com/akeyless-community/steampipe-plugin-akeyless/blob/main/go.mod#L1: repo link should be `akeyless-community`, because that's where this github repo exists.

**Comment by dboeke** [comment]
I have updated the akeyless plugin graphics on the steampipe hub.  Site is rebuilding now, should be up in 15min

![akeyless-social-graphic](https://github.com/user-attachments/assets/64b55c7d-dae7-4979-8cc8-aea9deb7fe2f)
![akeyless](https://github.com/user-attachments/assets/c5393bb7-7cca-4334-b5f8-f81e276cc9c7)

**Comment by akljph** [comment]
Thanks, @misraved. We just updated and everything should be good to go. 

Please confirm. 

Lastly, we will need to discuss how the plugin is built with our pipeline. 

> @akljph I think a few comments haven't been addressed as of now:
> 
> - https://github.com/akeyless-community/steampipe-plugin-akeyless/blob/main/config/akeyless.spc#L2 should include the org name in the plugin field. for instance, it should be `akeyless-community/akeyless`
> 
> - https://github.com/akeyless-community/steampipe-plugin-akeyless/blob/main/go.mod#L1: repo link should be `akeyless-community`, because that's where this github repo exists.

**Comment by misraved** [comment]
@akljph one final change that needs to be made for the plugin:

The `icon_url` in https://github.com/akeyless-community/steampipe-plugin-akeyless/blob/main/docs/index.md should be `/images/plugins/akeyless-community/akelyess.svg` instead of `/images/plugins/akeyless/logo.svg`.

Thanks!!

**Comment by akljph** [comment]
Hi @misraved. I updated both of those urls to `akeyless-community`
